# Basic
title: guoxuzan
subtitle: 极简主义者

#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
#description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://guoxuzan.com/">@guoxuzan</a>

url: "http://guoxuzan.com"
#url: "http://127.0.0.1:4000"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: guoxuzan
#    duoshuo : guoxuzan
    
# Social
social:
    weibo:   guoxuzan
    github:  guoxuzan
    mail:    guoxuzan@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
